version: '3.7'

services:
  #pubgame_app
  pubgame_app:
    container_name: pubgame_app_reactjs
    build: 
      context: .
      dockerfile: Dockerfile
    image: react-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - "/var/www/node_modules"
    ports:
      - 3001:3000